reviews:
  profile: assertive
  poem: false
  tools:
    shellcheck:
      enabled: true
    yamllint:
      enabled: true
    markdownlint:
      enabled: true
    cppcheck:
      enabled: true
    languagetool:
      enabled: true
      level: picky
      mother_tongue: en
  finishing_touches:
    docstrings:
      enabled: false
